"""Initial migration

Revision ID: 2ae35aa9fb8b
Revises: 
Create Date: 2026-05-20 09:21:33.322254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae35aa9fb8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_item',
    sa.Column('name', sa.String(length=100), nullable=False, comment='物品名稱'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='物品數量'),
    sa.Column('keeper', sa.String(length=50), nullable=False, comment='保管人'),
    sa.Column('location', sa.String(length=100), nullable=False, comment='存放位置'),
    sa.Column('last_withdraw_by', sa.String(length=50), nullable=True, comment='最近取出人'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_asset_item_quantity_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('name', sa.String(length=100), nullable=False, comment='公司中文名稱'),
    sa.Column('name_en', sa.String(length=100), nullable=False, comment='公司英文名稱'),
    sa.Column('logo', sa.String(length=255), nullable=True, comment='公司 Logo 路徑'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name_en')
    )
    op.create_table('department',
    sa.Column('name', sa.String(length=50), nullable=False, comment='部門名稱'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='部門描述'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='部門是否啟用'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project_item_status_option',
    sa.Column('item_type', sa.String(length=50), nullable=False, comment='子項目類型：todo/schedule/checkpoint'),
    sa.Column('value', sa.String(length=100), nullable=False, comment='狀態值'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_active', sa.Integer(), nullable=False, comment='是否啟用'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_option',
    sa.Column('option_type', sa.String(length=50), nullable=False, comment='選項類型：status/category'),
    sa.Column('value', sa.String(length=100), nullable=False, comment='選項值'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_active', sa.Integer(), nullable=False, comment='是否啟用'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('role_key', sa.String(length=50), nullable=False, comment='角色識別 Key'),
    sa.Column('role_name', sa.String(length=100), nullable=False, comment='角色名稱'),
    sa.Column('scope_type', sa.String(length=20), nullable=False, comment='資料範圍 own/department/all'),
    sa.Column('can_define_permissions', sa.Boolean(), nullable=False, comment='是否可定義新權限'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='角色說明'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_key')
    )
    op.create_table('asset_withdraw_record',
    sa.Column('asset_id', sa.Integer(), nullable=False, comment='資產項目 ID'),
    sa.Column('asset_name', sa.String(length=100), nullable=False, comment='取出時的物品名稱（快照）'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='取出數量'),
    sa.Column('withdrawer', sa.String(length=50), nullable=False, comment='取出人'),
    sa.Column('location', sa.String(length=100), nullable=False, comment='取出時的存放位置（快照）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_asset_withdraw_record_quantity_positive'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('department_id', sa.Integer(), nullable=False, comment='所屬部門 ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='群組名稱'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='群組是否啟用（1 啟用 / 0 停用）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('password', sa.String(length=255), nullable=False, comment='登入密碼雜湊值'),
    sa.Column('account', sa.String(length=100), nullable=False, comment='登入帳號'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='顯示名稱'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='電子郵件'),
    sa.Column('token_version', sa.Integer(), nullable=False, comment='JWT 版本號，用於登出後使舊 token 失效'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='所屬部門的 ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='帳號是否啟用（1 啟用 / 0 停用）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account')
    )
    op.create_table('archive_log',
    sa.Column('module_type', sa.String(length=20), nullable=False),
    sa.Column('week_start_date', sa.String(length=20), nullable=False, comment='封存週次的開始日期'),
    sa.Column('week_end_date', sa.String(length=20), nullable=False, comment='封存週次的結束日期'),
    sa.Column('archived_count', sa.Integer(), nullable=False, comment='本次封存寫入的資料筆數'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='本次封存對應的部門 ID'),
    sa.Column('archived_by_user_id', sa.Integer(), nullable=True, comment='執行封存動作的使用者 ID'),
    sa.Column('archived_by_name', sa.String(length=100), nullable=True, comment='執行封存動作的使用者名稱'),
    sa.Column('archived_at', sa.String(length=50), nullable=False, comment='封存發生時間'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_log',
    sa.Column('module_type', sa.String(length=20), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False, comment='被修改資料的主鍵 ID'),
    sa.Column('field_key', sa.String(length=100), nullable=False, comment='被修改欄位的程式識別 Key'),
    sa.Column('field_label', sa.String(length=100), nullable=False, comment='被修改欄位的顯示名稱'),
    sa.Column('old_value', sa.Text(), nullable=True, comment='修改前的欄位值'),
    sa.Column('new_value', sa.Text(), nullable=True, comment='修改後的欄位值'),
    sa.Column('owner_user_id', sa.Integer(), nullable=True, comment='此筆資料主要負責人的使用者 ID'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='此筆資料所屬部門的 ID'),
    sa.Column('edited_by_user_id', sa.Integer(), nullable=True, comment='實際執行編輯動作的使用者 ID'),
    sa.Column('edited_by_name', sa.String(length=100), nullable=True, comment='實際執行編輯動作的使用者名稱'),
    sa.Column('edited_at', sa.String(length=50), nullable=False, comment='編輯發生時間'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['edited_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pm_project',
    sa.Column('project_name', sa.String(length=255), nullable=False, comment='專案名稱'),
    sa.Column('vendor', sa.String(length=255), nullable=True, comment='廠商名稱'),
    sa.Column('summary', sa.Text(), nullable=True, comment='專案摘要說明'),
    sa.Column('execution_time', sa.String(length=255), nullable=True, comment='專案執行時間區間'),
    sa.Column('manager_user_id', sa.Integer(), nullable=True, comment='主管對應的使用者 ID'),
    sa.Column('manager_name', sa.String(length=100), nullable=True, comment='主管名稱快照'),
    sa.Column('assistants_text', sa.Text(), nullable=True, comment='協辦人員文字紀錄'),
    sa.Column('stage', sa.String(length=50), nullable=False, comment='專案執行階段'),
    sa.Column('priority', sa.String(length=50), nullable=False, comment='專案優先度'),
    sa.Column('planned_execution', sa.Text(), nullable=True, comment='本週預計執行內容'),
    sa.Column('last_week_progress', sa.Text(), nullable=True, comment='上週進度說明'),
    sa.Column('this_week_todo', sa.Text(), nullable=True, comment='本週待辦事項'),
    sa.Column('actual_execution', sa.Text(), nullable=True, comment='本週實際執行內容'),
    sa.Column('notes', sa.Text(), nullable=True, comment='補充備註'),
    sa.Column('custom_fields', sa.JSON(), nullable=True, comment='自訂欄位資料 JSON'),
    sa.Column('owner_user_id', sa.Integer(), nullable=True, comment='此專案主要負責人的使用者 ID'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='此專案所屬部門的 ID'),
    sa.Column('closed_at', sa.String(length=50), nullable=True, comment='專案結案時間'),
    sa.Column('cancelled_at', sa.String(length=50), nullable=True, comment='專案撤案時間'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='建立此筆資料的使用者 ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='最後更新此筆資料的使用者 ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['manager_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('name', sa.String(length=255), nullable=False, comment='專案名稱'),
    sa.Column('customer', sa.String(length=255), nullable=True, comment='客戶名稱'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='專案類別（CITD/SBIR…）'),
    sa.Column('group_id', sa.Integer(), nullable=True, comment='負責組別 FK'),
    sa.Column('group_name', sa.String(length=100), nullable=True, comment='負責組別名稱快照'),
    sa.Column('owner_user_id', sa.Integer(), nullable=True, comment='專案負責人 user FK（可選）'),
    sa.Column('owner_name', sa.String(length=100), nullable=True, comment='專案負責人名稱'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='專案狀態'),
    sa.Column('start_date', sa.String(length=20), nullable=True, comment='通用開始日'),
    sa.Column('pre_start_date', sa.String(length=20), nullable=True, comment='專案開始時間'),
    sa.Column('plan_start_date', sa.String(length=20), nullable=True, comment='計劃開始時間'),
    sa.Column('due_date', sa.String(length=20), nullable=True, comment='結束日期'),
    sa.Column('registered_address', sa.String(length=255), nullable=True, comment='營登地址'),
    sa.Column('mailing_address', sa.String(length=255), nullable=True, comment='通訊地址'),
    sa.Column('contact1', sa.String(length=100), nullable=True, comment='聯絡人 1'),
    sa.Column('contact_phone1', sa.String(length=50), nullable=True, comment='聯絡人 1 電話'),
    sa.Column('contact2', sa.String(length=100), nullable=True, comment='聯絡人 2'),
    sa.Column('contact_phone2', sa.String(length=50), nullable=True, comment='聯絡人 2 電話'),
    sa.Column('contact3', sa.String(length=100), nullable=True, comment='聯絡人 3'),
    sa.Column('contact_phone3', sa.String(length=50), nullable=True, comment='聯絡人 3 電話'),
    sa.Column('description', sa.Text(), nullable=True, comment='專案描述'),
    sa.Column('custom_fields', sa.JSON(), nullable=True, comment='自訂欄位 JSON'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='建立者 user ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='最後更新者 user ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rd_report',
    sa.Column('vendor', sa.String(length=255), nullable=True, comment='廠商名稱'),
    sa.Column('project_name', sa.String(length=255), nullable=False, comment='專案名稱'),
    sa.Column('executor_user_id', sa.Integer(), nullable=True, comment='執行人的使用者 ID'),
    sa.Column('executor_name', sa.String(length=100), nullable=True, comment='執行人名稱快照'),
    sa.Column('item_status', sa.String(length=50), nullable=False, comment='RD 工項狀態'),
    sa.Column('task_name', sa.String(length=255), nullable=True, comment='工項名稱'),
    sa.Column('item_content', sa.Text(), nullable=True, comment='工項內容說明'),
    sa.Column('planned_start', sa.String(length=50), nullable=True, comment='預計開始日期'),
    sa.Column('planned_end', sa.String(length=50), nullable=True, comment='預計完成日期'),
    sa.Column('actual_completed', sa.String(length=50), nullable=True, comment='實際完成日期'),
    sa.Column('notes', sa.Text(), nullable=True, comment='補充備註'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='此工項所屬部門的 ID'),
    sa.Column('closed_at', sa.String(length=50), nullable=True, comment='項目被確認完成的時間'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='建立此筆資料的使用者 ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='最後更新此筆資料的使用者 ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['executor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='使用者 ID'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色 ID'),
    sa.Column('job_title', sa.String(length=100), nullable=True, comment='職位名稱'),
    sa.Column('assigned_by', sa.Integer(), nullable=True, comment='指派此角色的使用者 ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pm_weekly_report',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='對應的 PM 專案 ID'),
    sa.Column('week_start_date', sa.String(length=20), nullable=False, comment='封存週次的開始日期'),
    sa.Column('week_end_date', sa.String(length=20), nullable=False, comment='封存週次的結束日期'),
    sa.Column('project_name_snapshot', sa.String(length=255), nullable=False, comment='封存當下的專案名稱快照'),
    sa.Column('vendor_snapshot', sa.String(length=255), nullable=True, comment='封存當下的廠商名稱快照'),
    sa.Column('summary_snapshot', sa.Text(), nullable=True, comment='封存當下的摘要快照'),
    sa.Column('manager_name_snapshot', sa.String(length=100), nullable=True, comment='封存當下的主管名稱快照'),
    sa.Column('assistants_snapshot', sa.Text(), nullable=True, comment='封存當下的協辦人員快照'),
    sa.Column('stage_snapshot', sa.String(length=50), nullable=False, comment='封存當下的執行階段快照'),
    sa.Column('priority_snapshot', sa.String(length=50), nullable=False, comment='封存當下的優先度快照'),
    sa.Column('planned_execution_snapshot', sa.Text(), nullable=True, comment='封存當下的預計執行內容快照'),
    sa.Column('last_week_progress_snapshot', sa.Text(), nullable=True, comment='封存當下的上週進度快照'),
    sa.Column('this_week_todo_snapshot', sa.Text(), nullable=True, comment='封存當下的本週待辦快照'),
    sa.Column('actual_execution_snapshot', sa.Text(), nullable=True, comment='封存當下的實際執行內容快照'),
    sa.Column('notes_snapshot', sa.Text(), nullable=True, comment='封存當下的備註快照'),
    sa.Column('owner_user_id', sa.Integer(), nullable=True, comment='此專案主要負責人的使用者 ID'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='此專案所屬部門的 ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['pm_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_checkpoint_item',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所屬專案'),
    sa.Column('checkpoint', sa.String(length=500), nullable=False, comment='查核點名稱'),
    sa.Column('review_date', sa.String(length=20), nullable=True, comment='查核時間'),
    sa.Column('assignee', sa.String(length=100), nullable=True, comment='細項功能負責人'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='狀態'),
    sa.Column('note', sa.String(length=255), nullable=True, comment='簡短備註'),
    sa.Column('description', sa.Text(), nullable=True, comment='查核描述（較長）'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序順序'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_schedule_item',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所屬專案'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='時程名稱'),
    sa.Column('assignee', sa.String(length=100), nullable=True, comment='細項功能負責人'),
    sa.Column('start_date', sa.String(length=20), nullable=False, comment='開始日期'),
    sa.Column('end_date', sa.String(length=20), nullable=False, comment='結束日期'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='狀態'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序順序'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_todo_item',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所屬專案'),
    sa.Column('item', sa.String(length=500), nullable=False, comment='待辦事項內容'),
    sa.Column('assignee', sa.String(length=100), nullable=True, comment='功能負責人'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='狀態'),
    sa.Column('due_date', sa.String(length=20), nullable=True, comment='須完成時間'),
    sa.Column('note', sa.Text(), nullable=True, comment='備註'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序順序'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rd_weekly_report',
    sa.Column('report_id', sa.Integer(), nullable=False, comment='對應的 RD 工項 ID'),
    sa.Column('week_start_date', sa.String(length=20), nullable=False, comment='封存週次的開始日期'),
    sa.Column('week_end_date', sa.String(length=20), nullable=False, comment='封存週次的結束日期'),
    sa.Column('vendor_snapshot', sa.String(length=255), nullable=True, comment='封存當下的廠商名稱快照'),
    sa.Column('project_name_snapshot', sa.String(length=255), nullable=False, comment='封存當下的專案名稱快照'),
    sa.Column('executor_name_snapshot', sa.String(length=100), nullable=True, comment='封存當下的執行人名稱快照'),
    sa.Column('item_status_snapshot', sa.String(length=50), nullable=False, comment='封存當下的工項狀態快照'),
    sa.Column('task_name_snapshot', sa.String(length=255), nullable=True, comment='封存當下的工項名稱快照'),
    sa.Column('item_content_snapshot', sa.Text(), nullable=True, comment='封存當下的工項內容快照'),
    sa.Column('planned_start_snapshot', sa.String(length=50), nullable=True, comment='封存當下的預計開始日期快照'),
    sa.Column('planned_end_snapshot', sa.String(length=50), nullable=True, comment='封存當下的預計完成日期快照'),
    sa.Column('actual_completed_snapshot', sa.String(length=50), nullable=True, comment='封存當下的實際完成日期快照'),
    sa.Column('notes_snapshot', sa.Text(), nullable=True, comment='封存當下的備註快照'),
    sa.Column('executor_user_id', sa.Integer(), nullable=True, comment='此工項執行人的使用者 ID'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='此工項所屬部門的 ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['executor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['rd_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rd_weekly_report')
    op.drop_table('project_todo_item')
    op.drop_table('project_schedule_item')
    op.drop_table('project_checkpoint_item')
    op.drop_table('pm_weekly_report')
    op.drop_table('user_role')
    op.drop_table('rd_report')
    op.drop_table('project')
    op.drop_table('pm_project')
    op.drop_table('change_log')
    op.drop_table('archive_log')
    op.drop_table('user')
    op.drop_table('group')
    op.drop_table('asset_withdraw_record')
    op.drop_table('role')
    op.drop_table('project_option')
    op.drop_table('project_item_status_option')
    op.drop_table('department')
    op.drop_table('company')
    op.drop_table('asset_item')
    # ### end Alembic commands ###
