"""add_pm_weekly_report_table

Revision ID: 48c7ed855dfd
Revises: ee9fb2110d7f
Create Date: 2026-05-22 15:37:25.185689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c7ed855dfd'
down_revision: Union[str, Sequence[str], None] = 'ee9fb2110d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
