"""add_pm_weekly_report_table_real

Revision ID: d4901972d08d
Revises: 48c7ed855dfd
Create Date: 2026-05-22 15:41:54.438852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4901972d08d'
down_revision: Union[str, Sequence[str], None] = '48c7ed855dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pm_weekly_report_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('table_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pm_weekly_report_table_id'), 'pm_weekly_report_table', ['id'], unique=False)
    op.create_index(op.f('ix_pm_weekly_report_table_user_id'), 'pm_weekly_report_table', ['user_id'], unique=False)
    op.create_index(op.f('ix_pm_weekly_report_table_week_start'), 'pm_weekly_report_table', ['week_start'], unique=False)
    op.create_table('rd_weekly_report_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('table_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rd_weekly_report_table_id'), 'rd_weekly_report_table', ['id'], unique=False)
    op.create_index(op.f('ix_rd_weekly_report_table_user_id'), 'rd_weekly_report_table', ['user_id'], unique=False)
    op.create_index(op.f('ix_rd_weekly_report_table_week_start'), 'rd_weekly_report_table', ['week_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rd_weekly_report_table_week_start'), table_name='rd_weekly_report_table')
    op.drop_index(op.f('ix_rd_weekly_report_table_user_id'), table_name='rd_weekly_report_table')
    op.drop_index(op.f('ix_rd_weekly_report_table_id'), table_name='rd_weekly_report_table')
    op.drop_table('rd_weekly_report_table')
    op.drop_index(op.f('ix_pm_weekly_report_table_week_start'), table_name='pm_weekly_report_table')
    op.drop_index(op.f('ix_pm_weekly_report_table_user_id'), table_name='pm_weekly_report_table')
    op.drop_index(op.f('ix_pm_weekly_report_table_id'), table_name='pm_weekly_report_table')
    op.drop_table('pm_weekly_report_table')
    # ### end Alembic commands ###
