"""reset_and_create_custom_weekly_tables

Revision ID: ee9fb2110d7f
Revises: 
Create Date: 2026-05-22 13:54:30.312767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee9fb2110d7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_spreadsheet')
    op.alter_column('project', 'custom_tables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='自訂表格 JSON',
               existing_comment='Custom tables JSON',
               existing_nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               comment='password hash',
               existing_comment='登入密碼雜湊值',
               existing_nullable=False)
    op.alter_column('user', 'account',
               existing_type=sa.VARCHAR(length=100),
               comment='login account',
               existing_comment='登入帳號',
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='display name',
               existing_comment='顯示名稱',
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='email',
               existing_comment='電子郵件',
               existing_nullable=True)
    op.alter_column('user', 'token_version',
               existing_type=sa.INTEGER(),
               comment='JWT token version',
               existing_comment='JWT 版本號，用於登出後使舊 token 失效',
               existing_nullable=False)
    op.alter_column('user', 'department_id',
               existing_type=sa.INTEGER(),
               comment='department ID',
               existing_comment='所屬部門的 ID',
               existing_nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='active flag',
               existing_comment='帳號是否啟用（1 啟用 / 0 停用）',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='帳號是否啟用（1 啟用 / 0 停用）',
               existing_comment='active flag',
               existing_nullable=False)
    op.alter_column('user', 'department_id',
               existing_type=sa.INTEGER(),
               comment='所屬部門的 ID',
               existing_comment='department ID',
               existing_nullable=True)
    op.alter_column('user', 'token_version',
               existing_type=sa.INTEGER(),
               comment='JWT 版本號，用於登出後使舊 token 失效',
               existing_comment='JWT token version',
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='電子郵件',
               existing_comment='email',
               existing_nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='顯示名稱',
               existing_comment='display name',
               existing_nullable=False)
    op.alter_column('user', 'account',
               existing_type=sa.VARCHAR(length=100),
               comment='登入帳號',
               existing_comment='login account',
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               comment='登入密碼雜湊值',
               existing_comment='password hash',
               existing_nullable=False)
    op.alter_column('project', 'custom_tables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Custom tables JSON',
               existing_comment='自訂表格 JSON',
               existing_nullable=True)
    op.create_table('weekly_spreadsheet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('week_start_date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('week_end_date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('weekly_spreadsheet_pkey'))
    )
    # ### end Alembic commands ###
